import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

// codeberg.org/uzu/strudel の公開ビルド(@strudel/*)のソースから、
// エクスポートされている関数名を抽出して strudel.d.ts を生成する。
// import せずソースを正規表現で読むため、実行時 import の不整合は無関係。

const PACKAGES = ['core', 'mini', 'tonal', 'webaudio', 'draw'];
const BASE = 'node_modules/@strudel';

// 明らかに内部/セットアップ用で楽曲記述に使わないものは除外する。
const DENY = new Set([
  'register', 'createParam', 'registerControl', 'registerSubControl',
  'registerSound', 'registerSynthSounds', 'registerZZFXSounds',
  'evalScope', 'evaluate', 'setStringParser', 'setVersionDefaultsEnabled',
  'logger', 'setLogger', 'getDrawContext', 'getTheme', 'controls',
  'getFrequency', 'getAudioContext', 'getAudioContextCurrentTime',
  'initAudio', 'initAudioOnFirstClick', 'webaudioOutput', 'webaudioScheduler',
  'aliasBank', 'soundMap', 'resetGlobalEffects', 'analysers', 'getAnalyserData',
]);

function extractExports(src) {
  const names = new Set();
  const add = (raw) => {
    const name = raw.trim().split(/\s+as\s+/).pop().trim();
    if (/^[A-Za-z_$][\w$]*$/.test(name)) names.add(name);
  };

  // export const { a, b, c } = ...
  for (const m of src.matchAll(/export\s+const\s*\{([^}]*)\}\s*=/g)) {
    m[1].split(',').forEach(add);
  }
  // export { a, b as c } [from '...']
  for (const m of src.matchAll(/export\s*\{([^}]*)\}/g)) {
    m[1].split(',').forEach(add);
  }
  // export const NAME = ...
  for (const m of src.matchAll(/export\s+const\s+([A-Za-z_$][\w$]*)\s*=/g)) add(m[1]);
  // export let NAME = ...
  for (const m of src.matchAll(/export\s+let\s+([A-Za-z_$][\w$]*)\s*=/g)) add(m[1]);
  // export function NAME(
  for (const m of src.matchAll(/export\s+(?:async\s+)?function\*?\s+([A-Za-z_$][\w$]*)/g)) add(m[1]);

  return names;
}

const all = new Set();

for (const pkg of PACKAGES) {
  const dir = path.join(BASE, pkg);
  let entries;
  try {
    entries = await readdir(dir);
  } catch {
    console.error(`[build-types] skip missing package: @strudel/${pkg}`);
    continue;
  }
  for (const file of entries) {
    if (!file.endsWith('.mjs')) continue;
    if (file.endsWith('.test.mjs') || file.includes('config')) continue;
    const src = await readFile(path.join(dir, file), 'utf8');
    for (const name of extractExports(src)) all.add(name);
  }
}

// 関数として扱うのは小文字始まり(Strudel の関数は camelCase)。
// 大文字始まり(Pattern/Hap/Fraction 等のクラス)と除外対象は外す。
const fns = [...all]
  .filter((n) => /^[a-z]/.test(n))
  .filter((n) => !DENY.has(n))
  .sort();

const methodLines = fns.map((n) => `  ${n}(...args: any[]): Pattern;`).join('\n');
const globalLines = fns.map((n) => `declare function ${n}(...args: any[]): Pattern;`).join('\n');

const out = `// AUTO-GENERATED by build-types.mjs — do not edit by hand.
// Source: @strudel/{${PACKAGES.join(',')}} (published build of codeberg.org/uzu/strudel).
// Regenerate with: npm run build-types
// 補完支援用。引数は any、戻り値は Pattern として扱い、関数名とメソッドチェーンを補完できるようにする。
// (型チェックは目的ではない。jsconfig.json では checkJs を有効にしないこと)

interface Pattern {
${methodLines}
  [key: string]: any;
}

${globalLines}

declare const Pattern: { prototype: Pattern };
`;

await mkdir('types', { recursive: true });
await writeFile('types/strudel.d.ts', out);
console.log(`[build-types] ${fns.length} functions -> types/strudel.d.ts`);
